name: Check workflow files

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    tags-ignore:
      - "*-release"
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
