name: Distribute

on:
  push:
    tags:
      - v*

jobs:
  distribute:
    name: Distribute widget assets
    runs-on: ubuntu-22.04

    env:
      API_URL: "https://erfgoedkit.nl/api/widget-v2"

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::308691726112:role/deploy-erfgoedkit-widget
          aws-region: eu-central-1

      - uses: actions/setup-node@v3
        with:
          node-version: "12"
          cache: "yarn"

      - run: yarn install

      - run: yarn build

      - name: Archive deploy output
        uses: actions/upload-artifact@v3
        with:
          name: yarn-run-deploy-output
          path: dist

      - name: Publish front-end
        run: |
          jsFile=$( find -s dist -maxdepth 1 -name '*.js' | head -n 1 )
          cssFile=$( find -s dist -maxdepth 1 -name '*.css' | head -n 1 )
          aws s3 cp "$jsFile" "s3://erfgoedkit-widget/${GITHUB_REF#refs/tags/}/script.js"
          aws s3 cp "$cssFile" "s3://erfgoedkit-widget/${GITHUB_REF#refs/tags/}/style.css"

          aws s3 cp --recursive dist s3://erfgoedkit-widget/

      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id="E2IGS3WXW2G03J" --path="/*"

  notification:
    name: Slack notification
    runs-on: ubuntu-22.04
    if: always()
    needs: [distribute]

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Send notification
        uses: edge/simple-slack-notify@master
        with:
          channel: "#ci"
          username: Publish
          status: ${{ (contains(needs.*.result, 'cancelled') && 'cancelled') || (contains(needs.*.result, 'failure') && 'failure') || 'success' }}
          success_text: ":octocat: Erfgoedkit widget is gepubliceerd. :rocket:"
          failure_text: ":octocat: Erfgoedkit widget publicatie heeft jammerlijk gefaald. :poop:"
          cancelled_text: ":octocat: Erfgoedkit widget publicatie is geannuleerd."
